# Generated by Django 3.1.5 on 2023-12-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_carrinho_relatorioentradasaida_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioentradasaida',
            name='descricao',
            field=models.CharField(default=11, max_length=150),
            preserve_default=False,
        ),
    ]
